# Generated by Django 3.2 on 2021-05-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagpubDev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Abstract',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='PublicationDate',
            field=models.DateField(null=True),
        ),
    ]
