# Generated by Django 3.2 on 2021-05-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagpubDev', '0002_auto_20210516_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tagpubDev.journal'),
        ),
    ]
