# Generated by Django 3.2 on 2021-05-23 20:13

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagpubDev', '0003_alter_article_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(max_length=64)),
                ('Description', models.TextField(max_length=1024, null=True)),
                ('Tokens', models.TextField(max_length=1024)),
                ('SearchIndex', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='PMID',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='author',
            name='ForeName',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='author',
            name='Initials',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='author',
            name='LastName',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='journal',
            name='ISOAbbreviation',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='journal',
            name='ISSN',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Title',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='Tags',
            field=models.ManyToManyField(to='tagpubDev.Tag'),
        ),
    ]
