# Generated by Django 3.2 on 2021-05-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagpubDev', '0004_auto_20210523_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.TextField(max_length=512),
        ),
    ]
