# Generated by Django 3.2 on 2021-05-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagpubDev', '0005_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ForeName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='LastName',
            field=models.CharField(max_length=128),
        ),
    ]
