# Generated by Django 3.2.3 on 2021-05-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagpubDev', '0006_auto_20210524_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='WikiID',
            field=models.CharField(default='Q', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='Tokens',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
