# Generated by Django 3.2.3 on 2021-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagpubDev', '0007_auto_20210524_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ForeName',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
