version: '3'

services:
  web:
    image: ghcr.io/semihsolmaz/tagpubweb@sha256:e667a456caf7797908d6478afa22e2fb065fcec6b41fcdf6bc9c87762a803095
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: tagpub
    volumes:
      - .:/tagpub
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY={{ django_secret_key}}
      - DATABASE_NAME=tagpub
      - DATABASE_USER=tagpubuser
      - DATABASE_PASS=tag147pub852
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENTREZ_API_KEY={{entrez_api_key}}
      - ENTREZ_EMAIL={{entrez_email}}
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tagpub
      - POSTGRES_USER=tagpubuser
      - POSTGRES_PASSWORD=tag147pub852

